Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"

  config.vm.network :forwarded_port, guest: 5432, host: 5433
  config.vm.network :forwarded_port, guest: 80, host: 8881

  #config.vm.synced_folder "../", "/project", :owner => 'root', create: true

  config.vm.provider :virtualbox do |vb|
    #vb.gui = true
    vb.name = "geonature"
    vb.memory = 12288
    vb.cpus = 4
  end

  # Configuration (adapter si besoin)
  config.vm.provision "shell", inline: <<-SHELL
cat << 'EOF' >> /root/.bashrc

#export GN_VERSION=""
#export GN_GITHUB_BASE_URL=""
#export GN_DATABASE_USERNAME=""
#export GN_DATABASE_PASSWORD=""
#export GN_BASE_URL=""

EOF
SHELL

  # Installation
  config.vm.provision "shell", path: "install.sh"

end
